name: Release
on: workflow_dispatch # manual trigger

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        #platform: [macos-latest, ubuntu-20.04, windows-latest]
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: 'Linen-dev/linen.dev'
          ref: 'main'

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './packages/spa/src-tauri -> target'

      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn' # Set this to npm, yarn or pnpm.

      - name: Install frontend dependencies
        # If you don't have `beforeBuildCommand` configured you may want to build your frontend here too.
        run: |
          yarn install
          yarn build:deps

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          REACT_APP_PUSH_SERVICE_URL: ${{ vars.REACT_APP_PUSH_SERVICE_URL }}
          REACT_APP_LINEN_BASE_URL: ${{ vars.REACT_APP_LINEN_BASE_URL }}
          REACT_APP_PUBLIC_POSTHOG_KEY: ${{ vars.REACT_APP_PUBLIC_POSTHOG_KEY }}
          REACT_APP_PUBLIC_POSTHOG_HOST: ${{ vars.REACT_APP_PUBLIC_POSTHOG_HOST }}
        with:
          tagName: 'v__VERSION__'
          releaseName: 'v__VERSION__' 
          releaseBody: 'v__VERSION__.'
          releaseDraft: false
          prerelease: false
          projectPath: './packages/spa'
